### ISSUE TITLE
Коли можна буде побачити проект?

### ISSUE THREAD

**Issue by dimaty** [liakhandrii/cv_project#1]
Якщо ви боїтеся давати його у відкритий доступ, може надіслати його якимось іншим чином.

**Comment by liakhandrii** [comment]
Я б із задоволенням надіслав, якби мав його. На жаль, в мене ще не знайлося
вільного часу для написання CV-проекту, сесія не дає відпочити.

В мене є проект, який підходить під Ваші вимоги (без жодних сторонніх
бібліотек), але він не є CV-проектом і написаний на Swift 1.2 (в новому
Xcode не компілюється). Прикріпляю сам проект в додатках і додаю промокоди
для App Store (цього проекту), щоб Ви мали можливість глянути не лише на
код.

Промокоди: H73K33HMTKM9, KE7JARLPFPKY, 76PRFKT7766K, RJ9AAEPKMLAX,
HNREA434JMMF

З повагою, Андрій Лях.
​
 liakhandrii-artpaper-30e5736fe97e.zip
<https://drive.google.com/file/d/0B_yTJBX2odgCc2JwQUhTV202TFE/view?usp=drive_web>
​

2016-05-11 13:14 GMT+03:00 Dmytro <notifications@github.com>:

**Comment by dimaty** [comment]
ок.
